name: CKO Seattle
favicon: null
layout_spectrum: 0.008940449450165033
typography_spectrum: 0.9954939065501094
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#f2be3b'
    - '#ffffff'
    - '#443e3b'
    - '#c4bdb8'
  brandStrength: 0.5681240686681122
  lightness: 0.39154231594875455
  saturation: 0.6320153730921447
  rhythmicContrast: 0.13595104473643005
purpose: []
